<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['account_import_app_description'] = 'The Account Import app performs bulk import of accounts using an uploaded file in comma separated values (CSV) format.';
$lang['account_import_app_name'] = 'Импорт учетной записи';
$lang['account_import_clear'] = 'Очистить';
$lang['account_import_csv_file'] = 'Файл CSV';
$lang['account_import_csv_file_not_found'] = ' CSV файл не найден';
$lang['account_import_download_csv_template'] = 'Скачать CSV шаблон';
$lang['account_import_import_already_in_progress'] = 'Импорт уже идет.';
$lang['account_import_import_complete'] = 'Импортирование завершено.';
$lang['account_import_import_log'] = 'Импорт журнала';
$lang['account_import_import_users'] = 'Импорт пользователей';
$lang['account_import_importing_user'] = 'Импорт пользователя';
$lang['account_import_no_data_found'] = 'Нет данных.';
$lang['account_import_no_entries'] = 'Никакие записи импорта не были найдены.';
$lang['account_import_number_of_records'] = 'Количество записей';
$lang['account_import_start_import'] = 'Начать импорт';
$lang['account_import_tooltip_csv'] = 'Ensure your CSV file is formatted properly - it should have values enclosed in quotations and separated by a comma ("value1","value2" etc.).';
$lang['account_import_unable_to_determine_running_state'] = 'Невозможно определить, если импорт работает.';
$lang['account_import_upload_csv_file'] = 'Загрузить CSV файл';
