<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['account_import_app_description'] = 'The Account Import app performs bulk import of accounts using an uploaded file in comma separated values (CSV) format.';
$lang['account_import_app_name'] = 'Account Import';
$lang['account_import_clear'] = 'Clear';
$lang['account_import_csv_file'] = 'CSV File';
$lang['account_import_csv_file_not_found'] = 'CSV file not found.';
$lang['account_import_download_csv_template'] = 'Download CSV Template';
$lang['account_import_import_already_in_progress'] = 'Import is already in progress.';
$lang['account_import_import_complete'] = 'Import complete.';
$lang['account_import_import_log'] = 'Import Log';
$lang['account_import_import_users'] = 'Import Users';
$lang['account_import_importing_user'] = 'Importing user';
$lang['account_import_no_data_found'] = 'No data found.';
$lang['account_import_no_entries'] = 'No import entries were found.';
$lang['account_import_number_of_records'] = 'Number of Records';
$lang['account_import_start_import'] = 'Start Import';
$lang['account_import_unable_to_determine_running_state'] = 'Unable to determine if import is running.';
$lang['account_import_upload_csv_file'] = 'Upload CSV File';
