<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['account_import_app_description'] = 'Aplikacja importująca konta przeprowadza masowy import kont użytkowników korzystając z wcześniej załadowanego pliku CSV.';
$lang['account_import_app_name'] = 'Import kont';
$lang['account_import_clear'] = 'Wyczyść';
$lang['account_import_csv_file'] = 'Plik CSV';
$lang['account_import_csv_file_not_found'] = 'Plik CSV nie został znaleziony.';
$lang['account_import_download_csv_template'] = 'Pobierz szablon CSV';
$lang['account_import_import_already_in_progress'] = 'Trwa import danych.';
$lang['account_import_import_complete'] = 'Import zakończony';
$lang['account_import_import_log'] = 'Dziennik importu';
$lang['account_import_import_users'] = 'Import użytkowników';
$lang['account_import_importing_user'] = 'Importowanie użytkowników';
$lang['account_import_no_data_found'] = 'Nie znaleziono danych.';
$lang['account_import_no_entries'] = 'Nie znaleziono danych do importu.';
$lang['account_import_number_of_records'] = 'Liczba rekordów';
$lang['account_import_start_import'] = 'Rozpocznij import';
$lang['account_import_tooltip_csv'] = 'Ensure your CSV file is formatted properly - it should have values enclosed in quotations and separated by a comma ("value1","value2" etc.).';
$lang['account_import_unable_to_determine_running_state'] = 'Nie można określić czy trwa import danych.';
$lang['account_import_upload_csv_file'] = 'Załaduj plik CSV';
